<?php
    if(empty($_POST["email"])){
	    header("location:index.php?empty=1");
	}
    else{
        $email=$_POST["email"];
		$password=$_POST["pass"];
		$conn=mysqli_connect("localhost","root","","details");
		$rs=mysqli_query($conn,"select * from details where email='$email'");
		if($r=mysqli_fetch_array($rs)){
			if($r["password"]==$password){
				setcookie("login",$email,time()+3600);
                header("location:profile.php");
			}
			else{
				header("location:index.php?invalid_pass");
			}
		}
		else{
			header("location:index.php?invalid_email");
		}
    }
?>	